@startuml
title WarmHouse Context Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "User", "A user of the warm house system")
Person(admin, "Administrator", "An administrator managing the system")
System(WarmHouseSystem, "WarmHouse System", "System controls temperature data, manage sensors and users")

System_Ext(api, "House Thermal Sensor", "External API for manage thermal sensor data")

Rel(user, WarmHouseSystem, "Uses the system")
Rel(admin,WarmHouseSystem,"Manages the system")
Rel(WarmHouseSystem,api,"Manage warm house sensor and fetching temperature data")

@enduml